spring:
        datasource:
                driverClassName: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/unilinkD
                username: root
                password: yVmonaed24
        jpa:
                hibernate.ddl-auto: update
                generate-ddl: true
                show-sql: true
             
